### ISSUE TITLE
Method predict uses new_data's first row as model input but associates result date with new_data's last timestamp + 1*freq

### ISSUE THREAD

**Issue by DsDev1** [Nixtla/mlforecast#109]
## Description

Method predict uses new_data's first row as model input but associates result date with new_data's last timestamp + 1*freq.
We can see from code example that first sample is being used as X but result is being associated with last timestamp available +1*freq.

## Reproducible example

```python

import lightgbm as lgb
from sklearn.ensemble import RandomForestRegressor

models = [
    lgb.LGBMRegressor(),
    RandomForestRegressor(random_state=0),
]

from mlforecast import MLForecast

fcst = MLForecast(
    models=models,
    freq=f'3600s',
)


# train_df definition

train_df[0:2]
# HUFL	HULL	MUFL	MULL	LUFL	LULL	OT	id_col	date
# 0	5.827	2.009	1.599	0.462	4.203	1.340	30.531000	1	2016-07-01 00:00:00
# 1	5.693	2.076	1.492	0.426	4.142	1.371	27.787001	1	2016-07-01 01:00:00


def inspect_input(x):
    from IPython.display import display
    print('inspect_input')
    display(x)
    return x

preds = fcst.predict(horizon=2, new_data=train_df[0:2], before_predict_callback=inspect_input)
# inspect_input
# id_col	HUFL	HULL	MUFL	MULL	LUFL	LULL
# 1	5.827	2.009	1.599	0.462	4.203	1.34

print(preds)
# 	id_col	date	LGBMRegressor	RandomForestRegressor
# 0	1	2016-07-01 02:00:00	30.530473	30.530290
# 1	1	2016-07-01 03:00:00	29.476429	28.449670



```

<details>
    <summary>Error message</summary>

```python
# Stacktrace
```
</details>

## Environment info
Install method (pip, conda, github): 
pip
Package version: 

0.6.0

**Comment by DsDev1** [comment]
The expected behavior would be to use the last row (the recent time-step) of the dataset instead of the first one, and the rest would work as expected. The current workaround to this issue is to pass only single row not df to clearly know what is the input and the expected output.

**Comment by iamyihwa** [comment]
Having same issue. 
Created a X variable which is very correlated with the y variable. 
However the model is not able to capture that at all. Perhaps due to the same issue as above. 

``` 

import pandas as pd

date_range = pd.date_range(start='2020-01-01', end='2021-01-01', freq='W')
df = pd.DataFrame(date_range, columns=['ds'])
df['unique_id'] = 1 
df['X'] = df['ds'].dt.year +  np.random.uniform( low = -1, high = 1, size= df.shape[0])*1000
df['y'] = df['X'] * 0.8 + np.random.rand()

cut_off = 20
train_df = df[:-cut_off]
train_df_X = train_df.loc[:,'X']
train_df_Y = train_df[['ds', 'y', 'unique_id']]
test_df = df[-cut_off:]
test_df_X = test_df.loc[:,['X', 'ds','unique_id']]
test_df_Y = test_df[['ds', 'y', 'unique_id']]
df.head()
from statsforecast import StatsForecast
StatsForecast.plot(df)
``` 

<img width="303" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/0a927802-ffc5-4014-98a1-5939e019a122">


```
import lightgbm as lgb
from window_ops.expanding import expanding_mean
from window_ops.rolling import rolling_mean

from mlforecast import MLForecast
from sklearn.linear_model import LinearRegression

mlf = MLForecast(
    models = [LinearRegression(), lgb.LGBMRegressor()],
    #lags=[1, 12],
    #lag_transforms={
    #    1: [expanding_mean],
    #    12: [(rolling_mean, 48)],
    #},
    freq = 'W', 
    #date_features = ['week', 'month', 'year']
)
def inspect_input(x):
    from IPython.display import display
    print('inspect_input')
    display(x)
    return x
prep_df =mlf.preprocess(train_df, id_col = 'unique_id', time_col = 'ds', target_col = 'y')
mlf.fit(train_df, id_col = 'unique_id', time_col = 'ds', target_col = 'y')
y_hat = mlf.predict(cut_off,  dynamic_dfs = [test_df_X],  before_predict_callback=inspect_input)
 
```
<img width="58" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/dd910fee-5913-463b-a164-df5c38f710ba">
The input passed to the model is always the first value of the training dataset. 
<img width="134" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/62245145-ea25-41d8-a0ce-a0286dba9ee9">

Therefore resulting forecast is a flat one, not being able to get the information from external variable. 

<img width="304" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/5245b920-4c85-4088-b570-ec3a2b4a59e1">


Suggested Change: 
In [core.py ](https://github.com/Nixtla/mlforecast/blob/main/mlforecast/core.py) 
Replace df to another variable in line 465 and 466 (since it seems to be using the global df variable, and do 'merge' on 'unique_id' and 'ds' ? 
<img width="286" alt="image" src="https://github.com/Nixtla/mlforecast/assets/12494156/d77d30b8-d031-419a-8a72-a59a4083e503">

@FedericoGarza @jose-moralez   what do you think???

**Comment by jmoralez** [comment]
Hi @iamyihwa, thanks for the thorough example. I believe this is the same as #122, the TLDR is that you have to set `static_features=[]` in your fit call, because right now mlforecast is treating `X` as a static feature and thus it only repeats its last value forward when predicting.

**Comment by iamyihwa** [comment]
Thanks @jmoralez  for your quick answer!
Yes!!!  indeed it solves the issue!! 

Thanks again to the team  for providing great tool and also for the help!!!

**Comment by jmoralez** [comment]
Closing as it seems we've solved the original issue.
