### ISSUE TITLE
level in prediction for 50

### ISSUE THREAD

**Issue by ahmad-shahi** [Nixtla/mlforecast#121]
When I use level 50, why it returns low and high for 50. 50 should be median and should return median. is it?

**Comment by jmoralez** [comment]
Thanks for raising this. Both interval methods compute the level from both sides, but we're not handling this case correctly. Will fix soon

**Comment by jmoralez** [comment]
Hey @ahmad-shahi. Are you using `level=[50]` with the `conformal_distribution` method? We would appreciate if you can provide a small snippet.

**Comment by ahmad-shahi** [comment]
I use level=[99, 95, 90, 80, 75, 50]. Also, I used only [50]:

![level_50](https://user-images.githubusercontent.com/24645016/233868601-47bad1c1-aa34-48b7-993a-ea56fcd6fb14.png)

**Comment by jmoralez** [comment]
`level` in this context means the width of the prediction interval, so in this case the interval uses the q25 and q75 as lower and upper limits.

**Comment by ahmad-shahi** [comment]
Thanks for the clarification.

**Comment by jmoralez** [comment]
The reason is to be consistent with the [forecast function](https://www.rdocumentation.org/packages/forecast/versions/8.4/topics/forecast) from the [forecast R package](https://pkg.robjhyndman.com/forecast/), where the lower and upper bounds of the interval are returned with similar namings (`Lo 50` and `Hi 50`).

Thanks for raising the issue, feel free to open another one if you encounter a problem. I'm closing this one.

**Comment by ahmad-shahi** [comment]
> The reason is to be consistent with the [forecast function](https://www.rdocumentation.org/packages/forecast/versions/8.4/topics/forecast) from the [forecast R package](https://pkg.robjhyndman.com/forecast/), where the lower and upper bounds of the interval are returned with similar namings (`Lo 50` and `Hi 50`).
> 
> Thanks for raising the issue, feel free to open another one if you encounter a problem. I'm closing this one.

Thanks for the good work and keep on.
