### ISSUE TITLE
Tuning LightGBM Models

### ISSUE THREAD

**Issue by pst2154** [Nixtla/mlforecast#123]
## Summary
- Tune lightgbm models, (or use an externally tuned lightgbm model)

## Motivation
- I don't see an easy way to tune the models

## Description
- hyperparameter tuning

## References
- https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258)

**Comment by mergenthaler** [comment]
@pst2154, thanks for the issue.  I think your message got lost during formating or something.

**Comment by pst2154** [comment]
fixed

**Comment by jmoralez** [comment]
Hi @pst2154. There are a couple of ways you can achieve this:
1. Using [MLForecast.cross_validation](https://nixtla.github.io/mlforecast/forecast.html#mlforecast.cross_validation). This allows you to evaluate the performance of your model across several validation sets. You can train a single model by setting `refit=False`, which should speed things up.
2. Using [LightGBMCV](https://nixtla.github.io/mlforecast/lgb_cv.html). This does something similar but trains several models simultaneously, which allows you to perform early stopping based on the performance across the whole forecasting window. There's an example on how to do this along with trial pruning in the [m4-cv notebook](https://www.kaggle.com/code/lemuz90/m4-competition-cv#Weekly).

We suggest using any of these approaches as opposed to just regular methods because otherwise you may find a model that is very good at predicting the next step but doesn't perform as well over your complete forecast horizon.

Please let us know if you have further doubts.

**Comment by pst2154** [comment]
Good point, will try that, thanks!

**Comment by jmoralez** [comment]
We also have this [tutorial](https://nixtla.github.io/mlforecast/docs/cross_validation.html) on cross validation.
