### ISSUE TITLE
lightgbmCV with MAE error

### ISSUE THREAD

**Issue by pst2154** [Nixtla/mlforecast#136]
Currently mlforecast gives an error if you do not select MAPE or RMSE as it says they are not implemented yet.

**Comment by pst2154** [comment]
I actually changed it locally and it worked perfectly fine with MAE. An easy fix to implement

**Comment by jmoralez** [comment]
Hi. Sorry for the late reply. I opened #137 for this, because the idea is allowing people to implement their own metrics, however I found that the current metrics are grouping by the index (which used to be the series ids but is now just a range index), so that change passes along the ids as well as the dates. I'll merge it soon and do a patch release.

**Comment by jmoralez** [comment]
We've released v0.7.3 and added [an example](https://nixtla.github.io/mlforecast/lgb_cv.html#using-a-custom-metric). Please let us know if this solves the issue.

**Comment by jmoralez** [comment]
Closing as I believe #137 solved this. Feel free to reopen.
