### ISSUE TITLE
Does mlforecast train a single global model or one model per serie?

### ISSUE THREAD

**Issue by kkckk1110** [Nixtla/mlforecast#299]
Hello! I found MLforecast really helpful. But I have a question about the model and training process. I followed the tutorial and trained XGBoost on my dataset, which consisted multiple time series. I wonder that, when training, do the time series with different ids share some parameters or training process? How does it work? Or could you please kindly refer to some documents where I can find some cues.

I tried to train the model on the whole dataset and train on a single time series alone. I found that, when I only input a time series to the model, the model produced better performance. Therefore, I am curious about the detailed training pipeline.

Thanks for your attention!

**Comment by jmoralez** [comment]
Hey @kkckk1110, we're glad you're finding it useful. A single model is trained using all of the series because it's usually the best performing approach (also the most efficient). If your series are very different you can try using the id as a feature, i.e. setting `static_features=['unique_id']` in the [fit method](https://nixtlaverse.nixtla.io/mlforecast/forecast.html#mlforecast-fit) which might help (for XGBoost you have to [set some arguments to enable categorical support](https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html#training-with-scikit-learn-interface)).
